{% set name = "premailer" %}
{% set version = "3.6.1" %}
{% set sha256 = "fcc1062329ba37668f95b2bf95e78d730eebf7851d742028251384a04e87fa22" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - setuptools
    
  run:
    - python
    - lxml
    - cssselect
    - cssutils
    - requests
    - cachetools

test:
  imports:
    - premailer

about:
  home: http://github.com/peterbe/premailer
  license: BSD3
  license_file: LICENSE
  summary: Turns CSS blocks into style attributes

extra:
  recipe-maintainers:
    - vamega
