travis:
  secure:
    BINSTAR_TOKEN: Ib/fLJwYaTFMIwu83SuVDWkLhzX47/HDtD84HyW2c/FRVfMMIcV3JglXGyW06QsK9z5QdgiaFaPAEDoK0AHKnRMLp/YLqhkUBv8ZKNvAb1ErF/KrBT2gwNsD0GK1+3I4JXiEpCEPTganZrtXQvVCgGTcjSLnxxWgKrXpKmL8LynszaX4dG07PmXGPkPcccJM3BYCDkW4zVv0iKYvlBDSkIp3icxOfaCsNGknHUY+1rBOeDiL/a3ADHSbsnQJ76ev6FupQKrPSaAWKiMJGU8slZqye9rGdGDQ603R41v4v0epelCzNCzoC2tpdg18ok8U7hnStPNWLV1x+DXwqHx8TWWY+pvILw24LOG4RCbgBa7keIfUC+erotr+wX8vWpULJ2v/27CyXDzry8FXyQWNNCZYHDiRqD3jgrQXPNIdFk9KO2Ek55QCdQLCREoIsVVGz9Aqvu8Uf/5oi/mA5GiAxrM6l1XrCW561hRdTpbtqzh1PH4PRSPFF7/scOr7i3l/oxLy8pKn6qqtAP5w83qtcdDiuGKwkj122v9pwqedGn+feWDkNtvO2+lYZU9O23a+yzwAP/zDiG9QNUuquzGI1HGEkh4R0bKhJqdJXdG1M1hfOPuyyhwBe7wVbcdXbtmD9vKe+w5OgY+djuDmcJRjILf3tArg32AZmj0RAZOyJ8k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
