travis:
  secure:
    BINSTAR_TOKEN: YfnkXBsfThwTcyPQ6UnAOUU8UDmJMhxQIw3rPwm7+vG9xCNzaAL1hT0yNZbQxfUu8JI85mHEDSSzFDb04aORhpISVNxOh5nVmIQ0BiUYn9vna5kfRgdhz9GDl6e5TQ/wvH3q1HS2gJtJEaeVBzoTZ+eS+O5utNK7UtZueYrrRF+yG0BDWoIicEBikwgH2IFoFSCfWGrANHq+efcUkEPgndLcTup3ymnaTjNsRN/ug7puGBUxsAKhiq6x0AIIe3voF3dEpT8PXaQEPrYo/mrL6eKJVJTdc91HCL6JbZBubyR7kvgnZEeT7giro9yQuIf/d1+zi+40VcF5QJrbAelOBdUn0QneiwcSje7qjFXoIm3RngPT6qnraDNRfLzLv/GMNw17jJtVg/sRl1ofMerYSHHJJDDupzo05RMldTfeuUdrWOcjgYOVdZkPG+E46wdh1fh5BrdlHgdKpVJQ6LTej+ZTOZQGukmkXwTz2OQGDWSOeOu0b2PT/Mx5aLusPL0uJ6gXeeQKlWrxNFoPLExOmKAln10F8YAMGL1RJvjD4/zti8eZeK/0Yz55VdJsUGr0HpsgKhWABJ1dmkqmqrm8hnASR0BJWAc+k6m+RnAawPE7BVsVlhqKcuTVW346AUXn/Xp9KJxztTCi+vOni4yHdVEaOwsESSS5iPXA8AwHUtY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
